### ISSUE TITLE
XC functional designated by julia symbol

### ISSUE THREAD

**Issue by unkcpz** [unkcpz/Libxc.jl#1]
The XC functional can be designated as following, using julia symbol.

```julia
Libxc.xc_func_init(ptr, :GGA_X_PBE, 1)
```

Adding a new function for xc_func_init()

**Comment by mfherbst** [comment]
I'm not sure what you had in mind with this issue @unkcpz. Perhaps it can now be closed due to #7.

**Comment by unkcpz** [comment]
Yes, thanks.
