### ISSUE TITLE
Release v0.1.3?

### ISSUE THREAD

**Issue by mfherbst** [unkcpz/Libxc.jl#8]
In DFTK, I would like to use the most current version of the library (with the symbolic names). Any reason to not make a release v0.1.3?

@unkcpz I'm happy to pull the trigger on the tagbot, but I wanted to leave that part up to you as the owner :smile:.

**Comment by unkcpz** [comment]
Sorry for did't see your message in time.
I was going to add some functional functionality to the new version, but I got delayed by something and forgot to submit the new version.
Now the new patch version is made.  @mfherbst

**Comment by mfherbst** [comment]
Many thanks!
